/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_linusdev_clgl_nat_glad_Glad */

#ifndef _Included_de_linusdev_clgl_nat_glad_Glad
#define _Included_de_linusdev_clgl_nat_glad_Glad
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    gladLoadGL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_clgl_nat_glad_Glad_gladLoadGL
  (JNIEnv *, jclass);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    glClear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad_glClear
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    glFinish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad_glFinish
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
