/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_linusdev_clgl_nat_NativeUtils */

#ifndef _Included_de_linusdev_clgl_nat_NativeUtils
#define _Included_de_linusdev_clgl_nat_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_linusdev_clgl_nat_NativeUtils
 * Method:    isNull
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_linusdev_clgl_nat_NativeUtils_isNull
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
