/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_linusdev_clgl_nat_wgl_WGL */

#ifndef _Included_de_linusdev_clgl_nat_wgl_WGL
#define _Included_de_linusdev_clgl_nat_wgl_WGL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_linusdev_clgl_nat_wgl_WGL
 * Method:    _wglGetCurrentContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_linusdev_clgl_nat_wgl_WGL__1wglGetCurrentContext
  (JNIEnv *, jclass);

/*
 * Class:     de_linusdev_clgl_nat_wgl_WGL
 * Method:    _wglGetCurrentDC
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_linusdev_clgl_nat_wgl_WGL__1wglGetCurrentDC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
