/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_linusdev_clgl_nat_glad_Glad */

#ifndef _Included_de_linusdev_clgl_nat_glad_Glad
#define _Included_de_linusdev_clgl_nat_glad_Glad
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    gladLoadGL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_clgl_nat_glad_Glad__1gladLoadGL
  (JNIEnv *, jclass);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    glClear
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad_glClear
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    glClearColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad_glClearColor
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    glFinish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad_glFinish
  (JNIEnv *, jclass);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    glBindFramebuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad_glBindFramebuffer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    _glGenFramebuffers
 * Signature: (ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad__1glGenFramebuffers
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    glGenFramebuffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_clgl_nat_glad_Glad_glGenFramebuffer
  (JNIEnv *, jclass);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    glCreateFramebuffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_clgl_nat_glad_Glad_glCreateFramebuffer
  (JNIEnv *, jclass);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    _glDeleteFramebuffers
 * Signature: (ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad__1glDeleteFramebuffers
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    glDeleteFramebuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad_glDeleteFramebuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    glNamedFramebufferRenderbuffer
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad_glNamedFramebufferRenderbuffer
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    _glGenRenderbuffers
 * Signature: (ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad__1glGenRenderbuffers
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    glGenRenderbuffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_clgl_nat_glad_Glad_glGenRenderbuffer
  (JNIEnv *, jclass);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    glCreateRenderbuffer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_clgl_nat_glad_Glad_glCreateRenderbuffer
  (JNIEnv *, jclass);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    _glDeleteRenderbuffers
 * Signature: (ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad__1glDeleteRenderbuffers
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    glDeleteRenderbuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad_glDeleteRenderbuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    glNamedRenderbufferStorage
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad_glNamedRenderbufferStorage
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    glBlitNamedFramebuffer
 * Signature: (IIIIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad_glBlitNamedFramebuffer
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    glNamedFramebufferReadBuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad_glNamedFramebufferReadBuffer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    glNamedFramebufferDrawBuffer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad_glNamedFramebufferDrawBuffer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    glGetString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_linusdev_clgl_nat_glad_Glad_glGetString
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    glEnable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad_glEnable
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    glDisable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad_glDisable
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    glDebugMessageCallback
 * Signature: (Lde/linusdev/clgl/nat/glad/custom/DebugMessageCallback;J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad_glDebugMessageCallback
  (JNIEnv *, jclass, jobject, jlong);

/*
* Class:     de_linusdev_clgl_nat_glad_Glad
* Method:    _glGenVertexArrays
* Signature: (IJ)V
*/
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad__1glGenVertexArrays
(JNIEnv *, jclass, jint, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    _glDeleteVertexArrays
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad__1glDeleteVertexArrays
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    glBindVertexArray
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad_glBindVertexArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    _glGenBuffers
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad__1glGenBuffers
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glad_Glad
 * Method:    _glDeleteBuffers
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glad_Glad__1glDeleteBuffers
  (JNIEnv *, jclass, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
