/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_linusdev_clgl_nat_NativeUtils */

#ifndef _Included_de_linusdev_clgl_nat_NativeUtils
#define _Included_de_linusdev_clgl_nat_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_linusdev_clgl_nat_NativeUtils
 * Method:    isNull
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_linusdev_clgl_nat_NativeUtils_isNull
        (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_clgl_nat_NativeUtils
 * Method:    _getNullPointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_linusdev_clgl_nat_NativeUtils__1getNullPointer
        (JNIEnv *, jclass);

/*
 * Class:     de_linusdev_clgl_nat_NativeUtils
 * Method:    sf_cl_mem
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_linusdev_clgl_nat_NativeUtils_sf_1cl_1mem
        (JNIEnv *, jclass);

/*
 * Class:     de_linusdev_clgl_nat_NativeUtils
 * Method:    getBufferFromPointer
 * Signature: (JI)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_de_linusdev_clgl_nat_NativeUtils_getBufferFromPointer
        (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
