/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_linusdev_clgl_vulkan_Vulkan */

#ifndef _Included_de_linusdev_clgl_vulkan_Vulkan
#define _Included_de_linusdev_clgl_vulkan_Vulkan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_linusdev_clgl_vulkan_Vulkan
 * Method:    _vkCreateInstance
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_cvg4j_nat_vulkan_Vulkan__1vkCreateInstance
  (JNIEnv *, jclass, jlong, jlong, jlong);

JNIEXPORT jint JNICALL Java_de_linusdev_cvg4j_nat_vulkan_Vulkan_callVulkanFunction1
        (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
