/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_linusdev_clgl_nat_glfw3_GLFWWindow */

#ifndef _Included_de_linusdev_clgl_nat_glfw3_GLFWWindow
#define _Included_de_linusdev_clgl_nat_glfw3_GLFWWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFWWindow
 * Method:    _glfwInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFWWindow__1glfwInit
        (JNIEnv *, jclass);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFWWindow
 * Method:    _glfwWindowHint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFWWindow__1glfwWindowHint
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFWWindow
 * Method:    _glfwSetErrorCallback
 * Signature: (Lde/linusdev/clgl/nat/glfw3/ErrorCallback;)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFWWindow__1glfwSetErrorCallback
        (JNIEnv *, jclass, jobject);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFWWindow
 * Method:    _glfwCreateWindow
 * Signature: (IILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFWWindow__1glfwCreateWindow
        (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFWWindow
 * Method:    _glfwTerminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFWWindow__1glfwTerminate
        (JNIEnv *, jclass);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFWWindow
 * Method:    _glfwPollEvents
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFWWindow__1glfwPollEvents
        (JNIEnv *, jclass);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFWWindow
 * Method:    _glfwMakeContextCurrent
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFWWindow__1glfwMakeContextCurrent
        (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFWWindow
 * Method:    _glfwDestroyWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFWWindow__1glfwDestroyWindow
        (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFWWindow
 * Method:    _glfwShowWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFWWindow__1glfwShowWindow
        (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFWWindow
 * Method:    _glfwSwapBuffers
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFWWindow__1glfwSwapBuffers
        (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFWWindow
 * Method:    _glfwSetWindowUserPointer
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFWWindow__1glfwSetWindowUserPointer
        (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFWWindow
 * Method:    _glfwSetInputMode
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFWWindow__1glfwSetInputMode
        (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFWWindow
 * Method:    _glfwSetWindowSize
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFWWindow__1glfwSetWindowSize
        (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFWWindow
 * Method:    _glfwSetWindowTitle
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFWWindow__1glfwSetWindowTitle
        (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFWWindow
 * Method:    _glfwSetWindowAttrib
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFWWindow__1glfwSetWindowAttrib
        (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFWWindow
 * Method:    _glfwGetWindowUserPointer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFWWindow__1glfwGetWindowUserPointer
        (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFWWindow
 * Method:    _glfwWindowShouldClose
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFWWindow__1glfwWindowShouldClose
        (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
