/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_linusdev_clgl_nat_cl_CL */

#ifndef _Included_de_linusdev_clgl_nat_cl_CL
#define _Included_de_linusdev_clgl_nat_cl_CL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_linusdev_clgl_nat_cl_CL
 * Method:    _clGetPlatformIDs
 * Signature: (ILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_clgl_nat_cl_CL__1clGetPlatformIDs
  (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     de_linusdev_clgl_nat_cl_CL
 * Method:    _clGetPlatformInfo
 * Signature: (JIILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_clgl_nat_cl_CL__1clGetPlatformInfo
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jobject);

/*
 * Class:     de_linusdev_clgl_nat_cl_CL
 * Method:    _clGetDeviceIDs
 * Signature: (JIILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_clgl_nat_cl_CL__1clGetDeviceIDs
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jobject);

/*
 * Class:     de_linusdev_clgl_nat_cl_CL
 * Method:    _clCreateContext
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;Ljava/lang/Class;JLjava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_de_linusdev_clgl_nat_cl_CL__1clCreateContext
  (JNIEnv *, jclass, jobject, jint, jobject, jclass, jlong, jobject);

/*
 * Class:     de_linusdev_clgl_nat_cl_CL
 * Method:    _clReleaseContext
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_clgl_nat_cl_CL__1clReleaseContext
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
