/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_linusdev_clgl_nat_glfw3_GLFW */

#ifndef _Included_de_linusdev_clgl_nat_glfw3_GLFW
#define _Included_de_linusdev_clgl_nat_glfw3_GLFW
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    _glfwInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW__1glfwInit
  (JNIEnv *, jclass);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    _glfwWindowHint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW__1glfwWindowHint
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    _glfwSetErrorCallback
 * Signature: (Lde/linusdev/clgl/nat/glfw3/custom/ErrorCallback;)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW__1glfwSetErrorCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    _glfwCreateWindow
 * Signature: (IILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW__1glfwCreateWindow
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    _glfwTerminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW__1glfwTerminate
  (JNIEnv *, jclass);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    _glfwPollEvents
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW__1glfwPollEvents
  (JNIEnv *, jclass);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    _glfwMakeContextCurrent
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW__1glfwMakeContextCurrent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    _glfwDestroyWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW__1glfwDestroyWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    _glfwShowWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW__1glfwShowWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    _glfwSwapBuffers
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW__1glfwSwapBuffers
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    _glfwSetWindowUserPointer
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW__1glfwSetWindowUserPointer
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    _glfwSetInputMode
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW__1glfwSetInputMode
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    _glfwSetWindowSize
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW__1glfwSetWindowSize
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    _glfwSetWindowTitle
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW__1glfwSetWindowTitle
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    _glfwSetWindowAttrib
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW__1glfwSetWindowAttrib
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    _glfwGetWindowUserPointer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW__1glfwGetWindowUserPointer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    _glfwWindowShouldClose
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW__1glfwWindowShouldClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    _glfwGetFramebufferSize
 * Signature: (JLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW__1glfwGetFramebufferSize
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    setJavaGLFWWindowClass
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW_setJavaGLFWWindowClass
  (JNIEnv *, jclass, jclass);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    glfwSetWindowSizeCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW_glfwSetWindowSizeCallback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    glfwSetFramebufferSizeCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW_glfwSetFramebufferSizeCallback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    glfwSetKeyCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW_glfwSetKeyCallback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    glfwSetCharCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW_glfwSetCharCallback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    glfwSetCursorPosCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW_glfwSetCursorPosCallback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    glfwSetCursorEnterCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW_glfwSetCursorEnterCallback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    glfwSetMouseButtonCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW_glfwSetMouseButtonCallback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    glfwSetScrollCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW_glfwSetScrollCallback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    glfwSetJoystickCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW_glfwSetJoystickCallback
  (JNIEnv *, jclass);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    glfwSetDropCallback
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW_glfwSetDropCallback
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    _glfwGetKeyName
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW__1glfwGetKeyName
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_linusdev_clgl_nat_glfw3_GLFW
 * Method:    glfwGetKeyScancode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_clgl_nat_glfw3_GLFW_glfwGetKeyScancode
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
