/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_linusdev_clgl_nat_cl_CL */

#ifndef _Included_de_linusdev_clgl_nat_cl_CL
#define _Included_de_linusdev_clgl_nat_cl_CL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_linusdev_clgl_nat_cl_CL
 * Method:    _clGetPlatformIDs
 * Signature: (ILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_clgl_nat_cl_CL__1clGetPlatformIDs
  (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     de_linusdev_clgl_nat_cl_CL
 * Method:    _clGetPlatformInfo
 * Signature: (IIILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_clgl_nat_cl_CL__1clGetPlatformInfo
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jobject);

/*
 * Class:     de_linusdev_clgl_nat_cl_CL
 * Method:    _clGetDeviceIDs
 * Signature: (IIILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_de_linusdev_clgl_nat_cl_CL__1clGetDeviceIDs
  (JNIEnv *, jclass, jlong , jint, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
