/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_linusdev_clgl_nat_Load */

#ifndef _Included_de_linusdev_clgl_nat_Load
#define _Included_de_linusdev_clgl_nat_Load
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_linusdev_clgl_nat_Load
 * Method:    _init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_Load__1init
        (JNIEnv *, jclass);

/*
 * Class:     de_linusdev_clgl_nat_Load
 * Method:    _close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_linusdev_clgl_nat_Load__1close
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
